"""
Django settings for userPortrait project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o-n3gi4kbi)%+82bp+53a4dqt89&z#02%ip8hby4%66+j)b^v6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 添加corsheaders跨域访问
    # 'corsheaders',
    # 添加kmeans定时任务
    # 'kmeansapp.kmeanstask',
    # 添加comprehensive定时任务
    # 'comprehensiveapp.comprehensivetask',
    # 添加dailyPrediction定时任务
    'dailyPredictionapp.dailyPredictiontask',
    # 'django_celery_beat',
    # 'django_crontab',
]

MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',  # # 添加corsheaders中间件，需放在django.middleware.common.CommonMiddleware之前
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'userPortrait.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'userPortrait.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

""" Celery 定时任务配置 """

# Redis 作为celery的消息队列
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'  # 后加
# CELERY_TIMEZONE = 'Asia/Shanghai'

# 重新连接配置
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# 使用crontab调度定时任务
from celery.schedules import crontab

# 定时任务调度器配置
CELERY_BEAT_SCHEDULE = {
    # 'kmeans_scheduled_task': {
    #     'task': 'kmeansapp.kmeanstask.kmeans_scheduled_task',
    #     'schedule': crontab(hour=0, minute=5),
    #     # 'schedule': 86400.0,  # 每天运行一次，单位为秒
    # },
    # 'comprehensive_scheduled_task_first': {
    #     'task': 'comprehensiveapp.comprehensivetask.comprehensive_scheduled_task',
    #     'schedule': crontab(hour=8, minute=30),
    # },
    # 'comprehensive_scheduled_task_second': {
    #     'task': 'comprehensiveapp.comprehensivetask.comprehensive_scheduled_task',
    #     'schedule': crontab(hour=16, minute=30),
    # },
    # 'comprehensive_scheduled_task_third': {
    #     'task': 'comprehensiveapp.comprehensivetask.comprehensive_scheduled_task',
    #     'schedule': crontab(hour=0, minute=30),
    # },
    'dailyPrediction_scheduled_task': {
        'task': 'dailyPredictionapp.dailyPredictiontask.dailyPrediction_scheduled_task',
        'schedule': crontab(hour=18, minute=20),
        # 'schedule': 1800.0,
    },
}

# 任务序列化格式
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# """ Corsheaders 跨域访问配置 """
# CORS_ALLOW_ALL_ORIGINS = True  # 允许所有来源
#
# # 允许的HTTP方法
# CORS_ALLOW_METHODS = [
#     "GET",
#     "POST",
# ]
#
# CORS_ALLOW_HEADERS = ['*']  # 允许所有请求头
#
# # 如果需要发送Cookie
# CORS_ALLOW_CREDENTIALS = True


# django-crontab定时任务
# CRONJOBS = [
#     ('45 22 * * *', 'myapp.tasks.my_scheduled_task'),  # 每分钟执行一次任务
# ]